---

- name: Add host entry
  lineinfile:
    dest: /etc/hosts
    regexp: " {{ ansible_hostname }}"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    owner: root
    group: root
    mode: 0644

- name: check if we have the systemd resolver
  register: has_systemd_resolved
  ignore_errors: True
  shell: systemctl status systemd-resolved

- name: disable systemd-resolved
  service:
    name: systemd-resolved
    enabled: no
    state: stopped
  when: has_systemd_resolved.rc == 0
