---

- name: install IPA packages (CentOS)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ipa-server
    - ipa-server-dns
  when: ansible_distribution == "CentOS"

- name: install IPA packages (Ubuntu)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - freeipa-server
    - freeipa-server-dns
  when: ansible_distribution == "Ubuntu"

- name: Install replication check script
  template: src="ipa-replica-check.sh" dest="/root/ipa-replica-check" mode=544

- name: Install replication test script
  template: src="ipa-replica-test.sh" dest="/root/ipa-replica-test" mode=544
