---

- assert:
    that: "ipa_type == 'replica' or ipa_type == 'firstborn'"
    msg: "Please only use allowed ipa_type:s"

- include_tasks: install.yml

- assert:
    that: ansible_fqdn | match(".+\\..+")
    msg: "Hostname ({{ansible_fqdn}}) not FQDN, /etc/hosts not correct?"

- name: Add host entry for self
  lineinfile:
    dest: /etc/hosts
    regexp: '\s{{ ansible_hostname }}'
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    owner: root
    group: root
    mode: 0644

- include_tasks: firstborn.yml
  when: ipa_type == "firstborn"

- stat: path="/etc/krb5.keytab"
  register: keytab

- include_tasks: client.yml
  when: ipa_type == "replica" and not keytab.stat.exists

- include_tasks: replica.yml
  when: ipa_type == "replica"

- include_tasks: cleanup.yml
