---

- assert:
    that:
      - "ipa_type == 'replica' or ipa_type == 'firstborn'"
    msg: "Please only use allowed ipa_type:s"

- include_tasks: install.yml

- include_tasks: dns.yml

- include_tasks: firstborn.yml
  when: ipa_type == "firstborn"

- include_tasks: replica.yml
  when: ipa_type == "replica"
