---

- assert:
    that:
      - "ipa_type == 'replica' or ipa_type == 'firstborn'"
    msg: "Please only use allowed ipa_type:s"

- include: install.yml

- include: dns.yml

- include: firstborn.yml
  when: ipa_type == "firstborn"

- include: replica.yml
  when: ipa_type == "replica"
